# CMake interface

.PHONY: all
all:
	@make -C build all

.PHONY: clean
clean:
	@make -C build clean

.PHONY: help
help:
	@make -C build help

.PHONY: depend
depend:
	@make -C build depend

.PHONY: edit_cache
edit_cache:
	@make -C build edit_cache

.PHONY: rebuild_cache
rebuild_cache:
	@make -C build rebuild_cache